# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GpgUnlock < Formula
  desc "Fetch GPG passphrase from your password manager and inject into gpg-agent cache"
  homepage "https://github.com/YewFence/gpg-unlock"
  version "1.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YewFence/gpg-unlock/releases/download/v1.6.2/gpg-unlock_1.6.2_darwin_amd64.tar.gz"
      sha256 "baa46621f9fd95a3420f3141c7a8cc124edaa8fcc2272d8357876a718890cfb1"

      define_method(:install) do
        bin.install "gpg-unlock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YewFence/gpg-unlock/releases/download/v1.6.2/gpg-unlock_1.6.2_darwin_arm64.tar.gz"
      sha256 "c1db47c112eaa1e0c7233aa2daee4b1b5c6c355c502152ee110b26030b028282"

      define_method(:install) do
        bin.install "gpg-unlock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/gpg-unlock/releases/download/v1.6.2/gpg-unlock_1.6.2_linux_amd64.tar.gz"
      sha256 "26a2a3be93d31118fb08930914b8d5c6847bbb4c33838fda08f8bd6d4f047d81"
      define_method(:install) do
        bin.install "gpg-unlock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/gpg-unlock/releases/download/v1.6.2/gpg-unlock_1.6.2_linux_arm64.tar.gz"
      sha256 "826ac4f01811c81fdd428eadef6dc5d6749ecbe64f959f1b2eef616994c92112"
      define_method(:install) do
        bin.install "gpg-unlock"
      end
    end
  end
end
