# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Infisical < Formula
  desc "CLI for the Infisical secret manager (yewfence fix fork)"
  homepage "https://github.com/YewFence/infisical-cli"
  version "0.43.60-yewfix3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.60-yewfix3/infisical-cli_0.43.60-yewfix3_darwin_amd64.tar.gz"
      sha256 "70a712883bf39a482b58ff3bab05338002b1ad31282b760ad6f6c178dbe45e75"

      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.60-yewfix3/infisical-cli_0.43.60-yewfix3_darwin_arm64.tar.gz"
      sha256 "e1db985a4d4704ee02ca6b645aaf5478e440e98ccdf946dacff0b6528fb2631d"

      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.60-yewfix3/infisical-cli_0.43.60-yewfix3_linux_amd64.tar.gz"
      sha256 "a9ae6144a702479bcac5f2a85d761578bcacf627854570193551d61acdef963d"
      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.60-yewfix3/infisical-cli_0.43.60-yewfix3_linux_arm64.tar.gz"
      sha256 "9295ca66526b017340d71dc9dd450d2877056bb51717b43da604c9d541e33b7b"
      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
