# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InfisicalAT04366Yewfix1 < Formula
  desc "CLI for the Infisical secret manager (yewfence fix fork)"
  homepage "https://github.com/YewFence/infisical-cli"
  version "0.43.66-yewfix1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.66-yewfix1/infisical-cli_0.43.66-yewfix1_darwin_amd64.tar.gz"
      sha256 "063de8da29ee890b1111c08e8dc73a38ec54b936961d5a5afa0775ddb8ba825d"

      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.66-yewfix1/infisical-cli_0.43.66-yewfix1_darwin_arm64.tar.gz"
      sha256 "c0c7acbe02c6adc4b26e59ebe818ad77aa69cfde772209e5c6d00b150316538a"

      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.66-yewfix1/infisical-cli_0.43.66-yewfix1_linux_amd64.tar.gz"
      sha256 "8e6ff642f507c1960c4176d2953c75db9d2bdf761f5f3a698d316a3df6851e3d"
      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YewFence/infisical-cli/releases/download/v0.43.66-yewfix1/infisical-cli_0.43.66-yewfix1_linux_arm64.tar.gz"
      sha256 "c143cd8c0bdd66717cdfc51447fe1beded5c3c03681ea71371bb1e5e9fe2dec0"
      define_method(:install) do
        bin.install "infisical"
        bash_completion.install "completions/infisical.bash" => "infisical"
        zsh_completion.install "completions/infisical.zsh" => "_infisical"
        fish_completion.install "completions/infisical.fish"
        man1.install "manpages/infisical.1.gz"
      end
    end
  end
end
